"""
Balance Sheet Data Importer

DESCRIPTION:
This module imports balance sheet data from Parquet storage files into the Excel 
balance sheets sheet. Handles multiple stock tickers with proper data organization
and Excel integration. Replicates functionality of xlwings backup but uses Parquet data.

INPUTS:
- Excel workbook: FinForge.xlsm with "balance sheets" sheet
- Ticker symbols: Located in row 4 of the Excel sheet
- Parquet files: Balance sheet data from Yahoo Finance (long format)
- Terminal window settings: Selected balance sheet line items

OUTPUTS:
- Updated "balance sheets" Excel sheet with financial data
- Console output showing import progress and status
- Error highlighting for missing data (light red cells)
- INDEX column management using the terminal window settings file

DEPENDENCIES:
- xlwings: Excel integration and manipulation
- pandas: Data processing and handling
- data_management.stock_data_manager: StockDataManager class for Parquet data access

RELATED FILES:
- Uses: data_management/stock_data_manager.py for data retrieval
- Called by: Electron (main.js) via Python subprocess
- Writes to: FinForge.xlsm "balance sheets" sheet
- Reads from: data/statement_settings.json generated by the terminal window
"""

import xlwings as xw
import pandas as pd
from pathlib import Path
import sys
import os
import json
import numbers
from collections import defaultdict

# Add parent directory to path for imports
sys.path.append(os.path.dirname(os.path.dirname(__file__)))
from data_management.stock_data_manager import StockDataManager, convert_fundamental_wide_to_long

# Font color definitions (RGB tuples for xlwings) - using text colors instead of background
RED_RGB = (255, 0, 0)      # Red text for missing data
DARK_RED_RGB = (139, 0, 0) # Dark red text for unavailable
YELLOW_RGB = (255, 255, 255)  # White text for empty values
NORMAL_RGB = (237, 125, 49)   # Orange text (#ED7D31) for normal/valid data

# Default Yahoo-style order template for balance sheet line items
YAHOO_BALANCE_SHEET_ORDER = [
    "Total Assets",
    "Current Assets",
    "Cash Cash Equivalents And Short Term Investments",
    "Cash And Cash Equivalents",
    "Cash And Short Term Investments",
    "Short Term Investments",
    "Receivables",
    "Accounts Receivable",
    "Inventory",
    "Prepaid Assets",
    "Other Current Assets",
    "Total Non Current Assets",
    "Net PPE",
    "Gross PPE",
    "Accumulated Depreciation",
    "Properties",
    "Land And Improvements",
    "Machinery Furniture Equipment",
    "Other Properties",
    "Leases",
    "Investments And Advances",
    "Investmentin Financial Assets",
    "Available For Sale Securities",
    "Other Investments",
    "Non Current Deferred Taxes Assets",
    "Non Current Deferred Assets",
    "Goodwill",
    "Intangible Assets",
    "Other Non Current Assets",
    "Total Liabilities Net Minority Interest",
    "Current Liabilities",
    "Accounts Payable",
    "Income Tax Payable",
    "Total Tax Payable",
    "Payables",
    "Current Accrued Expenses",
    "Payables And Accrued Expenses",
    "Commercial Paper",
    "Other Current Borrowings",
    "Current Debt",
    "Current Capital Lease Obligation",
    "Current Debt And Capital Lease Obligation",
    "Current Deferred Revenue",
    "Current Deferred Liabilities",
    "Other Current Liabilities",
    "Total Non Current Liabilities Net Minority Interest",
    "Long Term Debt And Capital Lease Obligation",
    "Long Term Debt",
    "Long Term Capital Lease Obligation",
    "Capital Lease Obligations",
    "Tradeand Other Payables Non Current",
    "Other Non Current Liabilities",
    "Total Equity Gross Minority Interest",
    "Stockholders Equity",
    "Common Stock Equity",
    "Total Capitalization",
    "Retained Earnings",
    "Capital Stock",
    "Common Stock",
    "Other Equity Adjustments",
    "Gains Losses Not Affecting Retained Earnings",
    "Net Tangible Assets",
    "Tangible Book Value",
    "Invested Capital",
    "Working Capital",
    "Total Debt",
    "Net Debt",
    "Share Issued",
    "Ordinary Shares Number",
    "Treasury Shares Number",
]

class BalanceSheetImporter:
    def __init__(self):
        # Get the project root directory (parent of Importing)
        project_root = Path(__file__).parent.parent
        data_path = project_root / "data"
        self.data_manager = StockDataManager(data_path)
        self.statement_settings_file = data_path / "statement_settings.json"
        self.sheet_name = "balance sheets"
        self.data_type = "balance_sheet_long"
        self.quarterly_data_type = "quarterly_balance_sheet"
        self.START_ROW = 4  # Where tickers are listed
        self.DATA_START_ROW = 7  # Where financial line items begin
    
    def _resolve_data_type(self):
        """Return the parquet data-type folder for the configured frequency."""
        settings = self._load_terminal_settings()
        frequency = settings.get("frequency", "annual") if isinstance(settings, dict) else "annual"
        if frequency == "quarterly":
            return self.quarterly_data_type
        return self.data_type

    def _load_ticker_df(self, ticker):
        """Load statement data for a ticker, melting wide format to long when needed."""
        df = self.data_manager.get_fundamental_data(ticker, self._resolve_data_type())
        if df.empty:
            return df
        if 'line_item' not in df.columns and 'index' in df.columns:
            df = convert_fundamental_wide_to_long(df)
        return df

    def _get_picked_periods(self):
        """Return {ticker: [date, ...]} for the current frequency from settings."""
        settings = self._load_terminal_settings()
        periods = settings.get("periods", {}) if isinstance(settings, dict) else {}
        if not isinstance(periods, dict):
            return {}
        freq_periods = periods.get(settings.get("frequency", "annual"), {})
        if not isinstance(freq_periods, dict):
            return {}
        result = {}
        for key, value in freq_periods.items():
            ticker = str(key).strip().upper()
            if not ticker:
                continue
            result[ticker] = [str(item).strip() for item in value] if isinstance(value, list) else []
        return result

    def _normalize_statement_date(self, value):
        """Return a clean YYYY-MM-DD string for a statement date value."""
        text = str(value).strip()
        parsed = pd.to_datetime(text, errors='coerce')
        if pd.isna(parsed):
            return text
        return parsed.strftime('%Y-%m-%d')

    def _resolve_statement_date(self, ticker, occurrence, date_values, picked_periods):
        """Pick the statement date for a ticker occurrence.

        An explicitly picked period (newest first) wins. When a ticker has no
        explicit picks, only the newest available period is used. Extra occurrences
        beyond the picks fall back to the Nth-most-recent date.
        """
        picked = picked_periods.get(ticker, []) if isinstance(picked_periods, dict) else []
        if picked:
            if occurrence <= len(picked):
                candidate = self._normalize_statement_date(picked[occurrence - 1])
                for date_value in date_values:
                    if self._normalize_statement_date(date_value) == candidate:
                        return date_value
            if occurrence > len(date_values):
                return None
            return date_values[occurrence - 1]
        if not date_values:
            return None
        return date_values[0]

    def _apply_period_dropdown(self, ws, col_index, date_values):
        """Add an Excel list-validation dropdown to the date cell for available periods."""
        labels = [self._normalize_statement_date(value) for value in date_values]
        labels = [label for label in labels if label][:24]
        if not labels:
            return
        formula = ",".join(labels)
        try:
            validation = ws.range((self.START_ROW + 1, col_index)).api.Validation
            validation.Delete()
            validation.Add(Type=3, AlertStyle=1, Operator=1, Formula1=formula)
        except Exception as exc:
            print(f"  Warning: could not add period dropdown to column {col_index}: {exc}")

    def _resolve_statement_date_with_selection(self, selected, ticker, occurrence, date_values, picked_periods):
        """Resolve the date: an existing dropdown selection wins, then settings, then newest."""
        if selected:
            candidate = self._normalize_statement_date(selected)
            for date_value in date_values:
                if self._normalize_statement_date(date_value) == candidate:
                    return date_value
        return self._resolve_statement_date(ticker, occurrence, date_values, picked_periods)

    def import_data(self, workbook_path=None):
        """
        Import balance sheet data from Parquet storage to Excel sheet
        """
        print(f"=== Starting Balance Sheet Import ===")
        
        try:
            # Connect to the Excel workbook
            if workbook_path:
                print(f"  Opening workbook: {workbook_path}")
                wb = xw.Book(workbook_path)
            else:
                try:
                    wb = xw.Book.caller()
                except:
                    # For testing outside Excel, try to connect to active workbook
                    print("⚠️  Running outside Excel - attempting to connect to active workbook")
                    wb = xw.books.active
                    if wb is None:
                        print("❌ No active Excel workbook found. Please run from Excel or open FinForge.xlsm")
                        return
            
            ws = wb.sheets[self.sheet_name]
            
            # Get used range with safety limits
            try:
                max_col = min(ws.api.UsedRange.Columns.Count, 100)
            except:
                try:
                    max_col = min(ws.range('A1').current_region.columns.count, 100)
                except:
                    max_col = 100
            
            print(f"Processing up to column: {max_col}")
            
            # ALWAYS get valid items and populate Column A first
            valid_items = self._get_valid_items_and_populate_column_a(ws, wb)
            
            if valid_items is None or len(valid_items) == 0:
                print("Warning: Could not determine valid items for INDEX")
                valid_items = []
            
            # Capture existing date selections (row 5) before clearing, so dropdown picks survive
            existing_dates = {}
            for col_index in range(2, max_col + 1):
                value = ws.range((self.START_ROW + 1, col_index)).value
                if value not in (None, ""):
                    existing_dates[col_index] = str(value).strip()
            
            # Clear all data columns before importing (preserve column A)
            self._clear_sheet_data(ws, len(valid_items) if valid_items else 200)
            
            # Resolve explicitly picked periods once (ticker -> [date, ...] newest first)
            picked_periods = self._get_picked_periods()
            
            # Process all columns (including INDEX columns)
            ticker_counter = defaultdict(int)
            success_count = 0
            
            for col_index in range(2, max_col + 1):  # Start from column 2 (skip column A)
                ticker_cell = ws.range((self.START_ROW, col_index))
                ticker_value = ticker_cell.value
                
                if not ticker_value:
                    continue
                
                ticker = str(ticker_value).strip().upper()
                print(f"\nProcessing column {col_index}: '{ticker}'")
                
                if ticker == "INDEX":
                    # Populate this column with INDEX items
                    self._write_index_items(ws, col_index, valid_items)
                    continue
                
                if ticker == "CUSTOM":
                    print(f"  Skipping CUSTOM column - left for user data")
                    continue  # Skip CUSTOM columns completely
                
                # Track occurrences for multiple periods
                ticker_counter[ticker] += 1
                occurrence = ticker_counter[ticker]
                print(f"  Occurrence #{occurrence} for ticker '{ticker}'")
                
                # Get data from Parquet storage
                df = self._load_ticker_df(ticker)
                
                if df.empty:
                    print(f"  No balance sheet data found for {ticker}")
                    self._mark_column_unavailable(ws, col_index, "No data found")
                    continue
                
                required_cols = {"line_item", "statement_date", "value"}
                if not required_cols.issubset(set(df.columns)):
                    print(f"  Invalid balance sheet format for {ticker}")
                    self._mark_column_unavailable(ws, col_index, "Invalid format")
                    continue
                
                # Get available statement dates (only those with actual data)
                date_values = df.loc[df["value"].notna(), "statement_date"].unique().tolist()
                if not date_values:
                    print(f"  No statement dates with data found for {ticker}")
                    self._mark_column_unavailable(ws, col_index, "No dates with data")
                    continue
                
                date_values = self._sort_statement_dates(date_values)
                print(f"  Found {len(date_values)} statement dates: {date_values}")
                
                # Add a dropdown to the date cell so the period can be picked in Excel
                self._apply_period_dropdown(ws, col_index, date_values)
                
                statement_date = self._resolve_statement_date_with_selection(
                    existing_dates.get(col_index), ticker, occurrence, date_values, picked_periods
                )
                if statement_date is None:
                    msg = f"Only {len(date_values)} periods available"
                    print(f"  {msg}")
                    self._mark_column_unavailable(ws, col_index, msg)
                    continue
                
                print(f"  Using statement date: '{statement_date}'")
                
                # Write statement date to Excel (normalized to YYYY-MM-DD)
                ws.range((self.START_ROW + 1, col_index)).value = self._normalize_statement_date(statement_date)
                
                stmt_df = df[(df["statement_date"] == statement_date) & (df["value"].notna())]
                stmt_data = stmt_df.groupby("line_item")["value"].first().to_dict()
                print(f"  Retrieved {len(stmt_data)} balance sheet items for '{statement_date}'")
                
                # Write data to Excel
                valid_count = self._write_data_to_excel(ws, col_index, stmt_data, valid_items)
                
                if valid_count > 0:
                    print(f"  Successfully imported {valid_count} items for {ticker} (#{occurrence})")
                    success_count += 1
                else:
                    print(f"  No valid data written for {ticker}")
            
            print(f"\n✅ Balance Sheet Import completed successfully")
            print(f"📊 Successfully processed {success_count} ticker columns")
            
        except Exception as e:
            print(f"❌ Error during balance sheet import: {str(e)}")
            import traceback
            traceback.print_exc()
            raise
    
    def _get_valid_items_and_populate_column_a(self, ws, wb):
        """Get valid items from the terminal settings file and ALWAYS populate Column A"""
        print("  Populating Column A with INDEX items...")
        
        # Get default items from the first available ticker in the sheet
        default_items = self._get_default_items_from_sheet(ws)
        if not default_items:
            # Fallback to AAPL if no ticker data is available
            df = self._load_ticker_df('AAPL')
            default_items = self._build_default_items_from_long_df(df)
        
        print(f"  Found {len(default_items)} default items from sheet or fallback data")
        
        # Read selected items from the terminal window settings file
        line_items = self._get_selected_items_from_terminal_settings("balanceSheet", default_items)
        
        # ALWAYS write to Column A
        row_index = self.DATA_START_ROW
        
        # Clear Column A first - clear enough rows to remove all old data from previous imports
        clear_end_row = min(self.DATA_START_ROW + 200, 1000)
        clear_range = ws.range((self.DATA_START_ROW, 1), (clear_end_row, 1))
        clear_range.value = None
        
        # Write items to Column A
        for item in line_items:
            col_a_cell = ws.range((row_index, 1))
            col_a_cell.value = item
            row_index += 1
        
        print(f"  Written {len(line_items)} INDEX items to Column A")
        
        return line_items

    def _load_terminal_settings(self):
        """Load the terminal window financial statement settings file"""
        default_settings = {
            "mode": "balanceSheet",
            "frequency": "annual",
            "periods": {},
            "display": {"mode": "millions", "divisor": 1000000},
            "balanceSheet": {"selected": []},
            "incomeStatement": {"selected": []},
        }

        if not self.statement_settings_file.exists():
            return default_settings

        try:
            with open(self.statement_settings_file, 'r', encoding='utf-8') as f:
                loaded = json.load(f)
        except (OSError, json.JSONDecodeError):
            return default_settings

        settings = default_settings.copy()
        settings["display"] = default_settings["display"].copy()
        settings["balanceSheet"] = default_settings["balanceSheet"].copy()
        settings["incomeStatement"] = default_settings["incomeStatement"].copy()

        if isinstance(loaded, dict):
            settings["mode"] = loaded.get("mode", settings["mode"])

            loaded_frequency = loaded.get("frequency")
            if loaded_frequency in ("annual", "quarterly"):
                settings["frequency"] = loaded_frequency

            loaded_periods = loaded.get("periods")
            if isinstance(loaded_periods, dict):
                settings["periods"] = loaded_periods

            display_settings = loaded.get("display")
            if isinstance(display_settings, dict):
                settings["display"].update(display_settings)

            balance_settings = loaded.get("balanceSheet")
            if isinstance(balance_settings, dict):
                settings["balanceSheet"].update(balance_settings)

            income_settings = loaded.get("incomeStatement")
            if isinstance(income_settings, dict):
                settings["incomeStatement"].update(income_settings)

        return settings

    def _get_selected_items_from_terminal_settings(self, section_name, default_items):
        """Return only the items explicitly selected in the terminal settings file."""
        settings = self._load_terminal_settings()
        section = settings.get(section_name, {}) if isinstance(settings, dict) else {}
        selected_items = section.get("selected", []) if isinstance(section, dict) else []
        selected_items = [str(item).strip() for item in selected_items if str(item).strip()]

        if not selected_items:
            print(f"  Warning: No selected items found for {section_name}; nothing will be imported")
            return []

        return selected_items

    def _get_default_items_from_sheet(self, ws):
        """Get default line item order from the first ticker with available data"""
        try:
            max_col = min(ws.api.UsedRange.Columns.Count, 100)
        except Exception:
            try:
                max_col = min(ws.range('A1').current_region.columns.count, 100)
            except Exception:
                max_col = 100
        
        for col_index in range(2, max_col + 1):
            ticker_cell = ws.range((self.START_ROW, col_index))
            ticker_value = ticker_cell.value
            if not ticker_value:
                continue
            
            ticker = str(ticker_value).strip().upper()
            if ticker in ["INDEX", "CUSTOM"]:
                continue
            
            df = self._load_ticker_df(ticker)
            if df.empty or 'line_item' not in df.columns:
                continue
            
            default_items = self._build_default_items_from_long_df(df)
            if default_items:
                return default_items
        
        return []

    def _build_default_items_from_long_df(self, df):
        """Build default item order using Yahoo template with data-driven fallback"""
        if df.empty or 'line_item' not in df.columns:
            return []
        
        if 'line_item_order' in df.columns:
            order_df = df[['line_item', 'line_item_order']].dropna()
            order_df = order_df.groupby('line_item', as_index=False)['line_item_order'].min()
            order_df = order_df.sort_values('line_item_order')
            available_items = order_df['line_item'].tolist()
        else:
            available_items = df['line_item'].dropna().tolist()
            available_items = list(dict.fromkeys(available_items))
        
        return self._apply_yahoo_order(available_items)

    def _apply_yahoo_order(self, available_items):
        """Apply the Yahoo template order and append remaining items in source order"""
        ordered = [item for item in YAHOO_BALANCE_SHEET_ORDER if item in available_items]
        ordered_set = set(ordered)
        remaining = [item for item in available_items if item not in ordered_set]
        return ordered + remaining

    def _sort_statement_dates(self, date_values):
        """Sort statement dates descending using parsed datetime when possible"""
        parsed_items = []
        unparsed_items = []
        
        for value in date_values:
            parsed_value = pd.to_datetime(value, errors='coerce')
            if pd.isna(parsed_value):
                unparsed_items.append(str(value))
            else:
                parsed_items.append((parsed_value, value))
        
        parsed_items.sort(key=lambda item: item[0], reverse=True)
        unparsed_items.sort(reverse=True)
        
        return [value for _, value in parsed_items] + unparsed_items
    
    def _find_or_create_settings_section(self, settings_ws, section_name):
        """Find or create a section in Settings sheet"""
        # Check first 100 columns for existing section
        for col in range(1, 101):
            header_value = settings_ws.range((1, col)).value
            if header_value and str(header_value).lower() == section_name.lower():
                return col
        
        # If not found, create in next available column
        last_col = 1
        for col in range(1, 101):
            if settings_ws.range((1, col)).value:
                last_col = col
        
        new_col = last_col + 1
        settings_ws.range((1, new_col)).value = section_name
        return new_col
    
    def _write_default_items_to_settings(self, settings_ws, col, default_items):
        """Write default items to Settings sheet - preserve formatting except errors"""
        # Clear existing items first in bulk - only clear values, preserve all formatting
        clear_range = settings_ws.range((3, col), (min(len(default_items) + 10, 1003), col))
        clear_range.value = None
        # Don't clear background colors anymore - preserve all background formatting
        
        # Write all default items starting from row 3
        for i, item in enumerate(default_items, start=3):
            item_cell = settings_ws.range((i, col))
            item_cell.value = item
            # Only clear error text colors, preserve all other formatting including backgrounds
            if item_cell.font.color in [RED_RGB, DARK_RED_RGB, YELLOW_RGB]:
                item_cell.font.color = NORMAL_RGB  # Set to orange for normal text
        
        print(f"Written {len(default_items)} items to Settings INDEX default column")
    
    def _read_configured_items(self, settings_ws, col, default_items):
        """Read configured items from Settings sheet - preserve formatting except errors"""
        configured_items = []
        invalid_items = []
        
        # Read from row 3 onwards
        for row in range(3, 1003):
            cell_value = settings_ws.range((row, col)).value
            if not cell_value:
                break
            
            item = str(cell_value).strip()
            if item in default_items:
                configured_items.append(item)
                # Clear any error text formatting for valid items - preserve background colors
                cell = settings_ws.range((row, col))
                if cell.font.color in [RED_RGB, DARK_RED_RGB, YELLOW_RGB]:
                    cell.font.color = NORMAL_RGB  # Set to orange for normal text
            else:
                invalid_items.append(item)
                # Clear invalid item but preserve all formatting
                invalid_cell = settings_ws.range((row, col))
                invalid_cell.value = None
                # Don't clear any colors anymore - preserve all formatting
        
        if invalid_items:
            print(f"Warning: Removed invalid items from config: {invalid_items}")
        
        if configured_items:
            print(f"Found {len(configured_items)} valid configured items")
        
        return configured_items
    
    def _clear_sheet_data(self, ws, num_items=None):
        """Clear all data columns (except Column A and CUSTOM columns) - preserve formatting"""
        try:
            last_col = min(ws.range((1,1)).end('right').column, 100)
        except:
            last_col = 100
        
        # Always clear enough rows to cover the maximum possible data
        # Use at least 200 rows or num_items, whichever is larger, to remove leftover rows from previous imports
        clear_rows = max(num_items if num_items else 0, 200)
        end_row = self.DATA_START_ROW + clear_rows
        end_row = min(end_row, 1000)  # Still apply absolute safety limit
        
        # Start from column 2 - Column A is always INDEX and handled separately
        for col in range(2, last_col + 1):
            # Skip CUSTOM columns - never touch user data
            header_value = ws.range((self.START_ROW, col)).value
            if header_value and str(header_value).strip().upper() == "CUSTOM":
                continue
            
            # Clear row 5 (dates) - ONLY VALUE, preserve formatting
            date_cell = ws.range((5, col))
            date_cell.value = None
            
            # Clear data values - preserve all formatting
            clear_range = ws.range((self.DATA_START_ROW, col), (end_row, col))
            clear_range.value = None
    
    def _write_index_items(self, ws, col_index, line_items):
        """Write line items to the specified INDEX column - preserve existing formatting"""
        print(f"  Writing INDEX items to column {col_index}")
        
        # Set the row 5 cell to "INDEX" label
        ws.range((self.START_ROW + 1, col_index)).value = "INDEX"
        
        row_index = self.DATA_START_ROW
        
        # Write items to this column
        for item in line_items:
            index_cell = ws.range((row_index, col_index))
            index_cell.value = item
            row_index += 1
        
        print(f"    Written {len(line_items)} INDEX items to column {col_index}")
    
    def _write_data_to_excel(self, ws, col_index, stmt_data, valid_items):
        """Write statement data to Excel with proper formatting - preserve existing formatting except for errors"""
        valid_count = 0
        display_divisor = self._get_display_divisor()
        
        # Process each row based on line items in column A
        row_index = self.DATA_START_ROW
        # Use the number of valid items as our limit if available, otherwise use safety limit
        max_rows = len(valid_items) if valid_items else 500
        
        while row_index < (self.DATA_START_ROW + max_rows):
            line_item_cell = ws.range((row_index, 1))
            line_item_value = line_item_cell.value
            
            if not line_item_value:
                break
            
            line_item = str(line_item_value).strip()
            data_cell = ws.range((row_index, col_index))
            
            # Skip items not in valid_items list - clear content but preserve formatting
            if valid_items is not None and line_item not in valid_items:
                data_cell.value = None
                # Don't change formatting - leave as is
                row_index += 1
                continue
            
            # Write data based on availability
            if line_item in stmt_data:
                value = stmt_data[line_item]
                if pd.isna(value) or value == "":
                    data_cell.value = "-"
                    # Apply error text color only for empty values
                    data_cell.font.color = YELLOW_RGB
                else:
                    data_cell.value = self._scale_value(value, display_divisor)
                    # Set normal data to orange color - preserves background colors
                    data_cell.font.color = NORMAL_RGB  # Orange color for valid data
                    valid_count += 1
            else:
                data_cell.value = "N/A"
                # Apply error text color only for missing data
                data_cell.font.color = RED_RGB
            
            row_index += 1
        
        return valid_count

    def _load_display_settings(self):
        default_settings = {"mode": "millions", "divisor": 1000000}

        try:
            if not self.statement_settings_file.exists():
                return default_settings

            with open(self.statement_settings_file, 'r', encoding='utf-8') as f:
                loaded = json.load(f)

            if isinstance(loaded, dict):
                display_settings = loaded.get('display')
                if isinstance(display_settings, dict):
                    settings = default_settings.copy()
                    settings.update(display_settings)
                    return settings

            return default_settings
        except (OSError, json.JSONDecodeError):
            return default_settings

    def _get_display_divisor(self):
        settings = self._load_display_settings()
        mode = str(settings.get('mode', 'millions')).lower()

        if mode == 'thousands':
            return 1000
        if mode == 'millions':
            return 1000000
        if mode == 'billions':
            return 1000000000
        if mode == 'custom':
            try:
                divisor = float(settings.get('divisor', 1))
                return divisor if divisor > 0 else 1
            except (TypeError, ValueError):
                return 1

        return 1000000

    def _scale_value(self, value, divisor):
        if divisor in [0, 0.0] or divisor is None:
            return value

        if isinstance(value, bool):
            return value

        if isinstance(value, numbers.Number):
            return value / divisor

        return value
    
    def _mark_column_unavailable(self, ws, col_index, message):
        """Mark a column as unavailable with error formatting"""
        print(f"  Marking column {col_index} as unavailable: {message}")
        
        # Set status message
        status_cell = ws.range((self.START_ROW + 1, col_index))
        status_cell.value = message
        status_cell.font.color = DARK_RED_RGB
        
        # Clear and mark data cells as N/A
        row_index = self.DATA_START_ROW
        max_rows = 500  # Safety limit
        while row_index < (self.DATA_START_ROW + max_rows):
            line_item_cell = ws.range((row_index, 1))
            if not line_item_cell.value:
                break
            
            data_cell = ws.range((row_index, col_index))
            data_cell.value = "N/A"
            data_cell.font.color = RED_RGB
            row_index += 1

# Excel-callable function
@xw.sub
def import_balance_sheets(workbook_path=None):
    """Import balance sheet data from Parquet to Excel - Called by VBA"""
    try:
        importer = BalanceSheetImporter()
        importer.import_data(workbook_path=workbook_path)
    except Exception as e:
        print(f"Error in import_balance_sheets: {str(e)}")
        raise

if __name__ == "__main__":
    # For testing
    importer = BalanceSheetImporter()
    importer.import_data()
